# Масштаб
SCALE = 1

# Параметры экрана и пола
SCREEN_WIDTH = 1200 * SCALE
LEVEL_WIDTH = 1200 * SCALE
SCREEN_HEIGHT = 800 * SCALE
FLOOR_HEIGHT = SCREEN_HEIGHT - 110 * SCALE
HEALTH_POINT_POSITION_X = 45 * SCALE
HEALTH_POINT_POSITION_Y = 45 * SCALE
HEALTH_POINT_SIZE = 25 * SCALE

# Platform parameters
PLATFORM_HEIGHT = 80 * SCALE
PLATFORM_WIDTH = 320 * SCALE
PLATFORM_POSITION_Y = FLOOR_HEIGHT - PLATFORM_HEIGHT

FLOOR_POSITION = [-10 * LEVEL_WIDTH, FLOOR_HEIGHT]
FLOOR_DEPTH = 110 * SCALE

SECOND_PLATFORM_POSITION = [250, PLATFORM_POSITION_Y]
THIRD_PLATFORM_POSITION = [750, PLATFORM_POSITION_Y]
FOURTH_PLATFORM_POSITION = [750, PLATFORM_POSITION_Y - PLATFORM_HEIGHT]

FLOOR_SIZE = [LEVEL_WIDTH * 10, FLOOR_HEIGHT]
SECOND_PLATFORM_SIZE = [PLATFORM_WIDTH * 2, PLATFORM_HEIGHT * 2]
THIRD_PLATFORM_SIZE = [PLATFORM_WIDTH, PLATFORM_HEIGHT]
FOURTH_PLATFORM_SIZE = [PLATFORM_WIDTH, PLATFORM_HEIGHT]

# Player parameters
PLAYER_HEIGHT = 150 * SCALE
PLAYER_WIDTH = 90 * SCALE
START_POSITION_X = 50
START_POSITION_Y = FLOOR_HEIGHT - PLAYER_HEIGHT
PLAYER_SPEED = 500 * SCALE
JUMP_SPEED = 650 * SCALE
PLAYER_SPEED_LIST = [0, 0]
HEALTH_POINTS = 3
PLAYER_DAMAGE = 1


# Camera parameters
CAMERA_X = 0 * SCALE
CAMERA_Y = 0 * SCALE
MAX_PLAYER_CENTER_DISTANCE_X = 100 * SCALE
BORDER_XL = (SCREEN_WIDTH / 2) - MAX_PLAYER_CENTER_DISTANCE_X
BORDER_XR = (SCREEN_WIDTH / 2) + MAX_PLAYER_CENTER_DISTANCE_X
BORDER_YH = FLOOR_DEPTH
BORDER_YD = FLOOR_HEIGHT - PLAYER_HEIGHT

# Enemy parameters
ENEMY_HEIGHT = 150 * SCALE
ENEMY_WIDTH = 90 * SCALE
ENEMY_POSITION_Y = FLOOR_HEIGHT - ENEMY_HEIGHT
FIRST_ENEMY_POSITION = [350, ENEMY_POSITION_Y - PLATFORM_HEIGHT]
SECOND_ENEMY_POSITION = [500, ENEMY_POSITION_Y]
ENEMY_SPEED = 10 * SCALE
HEALTH_POINTS_ENEMY = 1
ENEMY_DAMAGE = 1

# Ось и циферки
FONT_SIZE = int(30 * SCALE)

# Физические константы
FPS = 60
G = 1500 * SCALE
DELTA_T = 1/FPS
WIN_POSITION = (1500, FLOOR_HEIGHT - PLAYER_HEIGHT)

# Картинки
IMAGES_DIRECTORY = "source/images/"
BACKGROUND_FILENAME = IMAGES_DIRECTORY + "wallpaper_cut.jpg"
FLOOR_FILENAME = IMAGES_DIRECTORY + "floor.png"
PLAYER_FILENAME = IMAGES_DIRECTORY + "player.jpg"
PLAYER_ATTACK_FILENAME = IMAGES_DIRECTORY + "player_attack.png"
ENEMY_FILENAME = IMAGES_DIRECTORY + "enemy.jpg"
PLATFORM_FILENAME = IMAGES_DIRECTORY + "platform.png"
HEALTH_POINT_FILENAME = IMAGES_DIRECTORY + "healt_point.png"

# Звуки
SOUND_DIRECTORY = "source/sounds/"
BACK_MUSIC_1 = SOUND_DIRECTORY + "Back_music_1.mp3"
BUM_1 = SOUND_DIRECTORY + "Bym_1.mp3"
