# Масштаб
SCALE = 1

# Параметры экрана и пола
SCREEN_WIDTH = 1200 * SCALE
SCREEN_HEIGHT = 800 * SCALE
FLOOR_HEIGHT = SCREEN_HEIGHT - 110 * SCALE
HEALTH_POINT_POSITION_X = 45 * SCALE
HEALTH_POINT_POSITION_Y = 45 * SCALE
HEALTH_POINT_SIZE = 25 * SCALE

# Player parameters
PLAYER_HEIGHT = 150 * SCALE
PLAYER_WIDTH = 90 * SCALE
VIEW_RADIUS = 200
START_POSITION_X = 150
START_POSITION_Y = FLOOR_HEIGHT - PLAYER_HEIGHT
PLAYER_SPEED = 500 * SCALE
GENERAL_MOVEMENT_SPEED = PLAYER_SPEED
JUMP_SPEED = 650 * SCALE
PLAYER_SPEED_LIST = [0, 0]
HEALTH_POINTS = 3
TIME_OF_ATTACK = 15
PLAYER_DAMAGE = 1


# Platform parameters
PLATFORM_HEIGHT = 90 * SCALE
PLATFORM_WIDTH = 350 * SCALE
PLATFORM_POSITION_Y = FLOOR_HEIGHT - PLATFORM_HEIGHT
FLOOR_DEPTH = 110 * SCALE
DEFAULT_PLATFORM_SIZE = [PLATFORM_WIDTH, PLATFORM_HEIGHT]

# First level parameters
# Позиции пола и стен всегда первые в списке
FLOOR_POSITION = [-400, FLOOR_HEIGHT]
FLOOR_SIZE = [10*SCREEN_WIDTH, FLOOR_DEPTH]
LEFT_WALL_POSITION = [-400, FLOOR_HEIGHT - SCREEN_HEIGHT]
LEFT_WALL_SIZE = [100, SCREEN_HEIGHT]
# Позиции платформ на уровне
FIRST_PLATFORM_POSITION = [300, PLATFORM_POSITION_Y]
SECOND_PLATFORM_POSITION = [900, PLATFORM_POSITION_Y]
THIRD_PLATFORM_POSITION = [900, PLATFORM_POSITION_Y - PLATFORM_HEIGHT]
FOURTH_PLATFORM_POSITION = [2100, PLATFORM_POSITION_Y- PLATFORM_HEIGHT]
FIVTH_PLATFORM_POSITION = [3000, PLATFORM_POSITION_Y - PLATFORM_HEIGHT]
SIX_PLATFORM_POSITION = [4050, PLATFORM_POSITION_Y]
SEVEN_PLATFORM_POSITION = [4800, PLATFORM_POSITION_Y - PLATFORM_HEIGHT*5]
# Размеры платформ
FIRST_PLATFORM_SIZE = DEFAULT_PLATFORM_SIZE
SECOND_PLATFORM_SIZE = DEFAULT_PLATFORM_SIZE
THIRD_PLATFORM_SIZE = DEFAULT_PLATFORM_SIZE
FOURTH_PLATFORM_SIZE = [PLATFORM_WIDTH*2, PLATFORM_HEIGHT*2]
FIVTH_PLATFORM_SIZE = [PLATFORM_WIDTH*3, PLATFORM_HEIGHT*2]
SIX_PLATFORM_SIZE = [PLATFORM_WIDTH*0.7, PLATFORM_HEIGHT]
SEVEN_PLATFORM_SIZE = [PLATFORM_WIDTH*0.7, PLATFORM_HEIGHT]
# Позиция выигрывшыной платформы
WIN_POSITION = [5150, PLATFORM_POSITION_Y]
WIN_SIZE = [PLATFORM_WIDTH*0.3, PLATFORM_HEIGHT]

# Camera parameters
CAMERA_X = 0 * SCALE
CAMERA_Y = 0 * SCALE
MAX_PLAYER_CENTER_DISTANCE_X = 100 * SCALE
BORDER_XL = (SCREEN_WIDTH / 2) - MAX_PLAYER_CENTER_DISTANCE_X
BORDER_XR = (SCREEN_WIDTH / 2) + MAX_PLAYER_CENTER_DISTANCE_X
BORDER_YH = FLOOR_DEPTH
BORDER_YD = FLOOR_HEIGHT - PLAYER_HEIGHT

# Enemy parameters
ENEMY_HEIGHT = 150 * SCALE
ENEMY_WIDTH = 90 * SCALE
ENEMY_POSITION_Y = FLOOR_HEIGHT - ENEMY_HEIGHT
FIRST_ENEMY_POSITION = [350, ENEMY_POSITION_Y - PLATFORM_HEIGHT]
SECOND_ENEMY_POSITION = [500, ENEMY_POSITION_Y]
ENEMY_SPEED = 10 * SCALE
HEALTH_POINTS_ENEMY = 3
ENEMY_DAMAGE = 1

# Ось и циферки
FONT_SIZE = int(30 * SCALE)

# Физические константы
FPS = 60
G = 1500 * SCALE
DELTA_T = 1/FPS

# Картинки
IMAGES_DIRECTORY = "source/images/"
BACKGROUND_FILENAME = IMAGES_DIRECTORY + "wallpaper_cut.jpg"
FLOOR_FILENAME = IMAGES_DIRECTORY + "floor.png"
PLAYER_FILENAME = IMAGES_DIRECTORY + "player.jpg"
PLAYER_ATTACK_FILENAME = IMAGES_DIRECTORY + "player_attack.png"
ENEMY_FILENAME = IMAGES_DIRECTORY + "enemy.jpg"
PLATFORM_FILENAME = IMAGES_DIRECTORY + "platform.png"
HEALTH_POINT_FILENAME = IMAGES_DIRECTORY + "healt_point.png"

# Звуки
SOUND_DIRECTORY = "source/sounds/"
BACK_MUSIC_1 = SOUND_DIRECTORY + "Back_music_1.mp3"
BUM_1 = SOUND_DIRECTORY + "Bym_1.mp3"

# Параметры кнопок
BUTTON_NEW_GAME_SIZE_WIDTH = 200
BUTTON_NEW_GAME_SIZE_HEIGHT = 50
BUTTON_EXIT_SIZE_WIDTH = 200
BUTTON_EXIT_SIZE_HEIGHT = 50
BUTTON_EXIT_POSITION_X = 500
BUTTON_EXIT_POSITION_Y = 500
BUTTON_NEW_GAME_POSITION_X = 500
BUTTON_NEW_GAME_POSITION_Y = 350
